-- CreateTable
CREATE TABLE "SignalRecipientNumber" (
    "id" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SignalRecipientNumber_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SignalRecipientNumber_phoneNumber_key" ON "SignalRecipientNumber"("phoneNumber");

-- Data migration: preserve any existing SignalConfig.recipientNumber value
-- as a SignalRecipientNumber row before the column is dropped below. IDs are
-- normally generated by the app as cuid()s, but this is a one-off, pure-SQL
-- data move with no app process involved — gen_random_uuid() (built into
-- Postgres core since v13, no extension needed) is used instead. The column
-- is still just `TEXT`, so a UUID-shaped id here is fine; Prisma never
-- validates existing id formats, only generates new ones going forward.
INSERT INTO "SignalRecipientNumber" ("id", "phoneNumber", "isActive", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, "recipientNumber", true, now(), now()
FROM "SignalConfig"
WHERE "recipientNumber" IS NOT NULL AND "recipientNumber" != ''
ON CONFLICT ("phoneNumber") DO NOTHING;

-- AlterTable
ALTER TABLE "SignalConfig" DROP COLUMN "recipientNumber";
